# render.yaml

name: example-service-name
region: us-west
branch: main
rootDir: Backend/api
runtime: python
buildCommand: pip install -r requirements.txt
startCommand: /home/senerwa/Web/FlaskApi/venv/bin/gunicorn app:app
